Generate coin.TRANSFER events for gas, coinbase, crosschain
kadena-io/chainweb-node pull request #1217
Opened 2021-04-16 13:39 UTC by sirlensalot

With this change all changes to `coin` accounts will be visible via `coin.TRANSFER` events. This is also the model for a new KIP to require `TRANSFER` events for burn and create by using an empty account `""` to indicate:

- Gas payment: transfer from `sender` to miner
- Coinbase: transfer from `""` to miner
- Crosschain step 1: transfer from `sender` to `""`
- Crosschain step 2: transfer from `""` to `receiver`

TODO investigate if allocation release can be detected for generating events.

FORKING CHANGE.

2021-04-19 15:45 UTC, larskuhtz requested changes
The changes look good to me. I would have expected that some golden test results would need to be updated. Also, are there any unit tests for events? If not, it might be good to add those.

2021-04-19 15:45 UTC, larskuhtz commented on stack.yaml
> +    commit: ccce78004d567966f5cfff131287fbdb3bf63121
This pin must also be updated in `cabal.project` and `project.nix`.

2021-04-19 15:45 UTC, larskuhtz commented on src/Chainweb/Version.hs
> +pactGenerateEvents Testnet04 = (>= 1_140_000) -- 2021-05-06T13:47:27
👍 Looks good. These there the estimates that I get base on current block heights:

mainnet: 2021-05-07 14:37:06
testnet: 2021-05-06 13:54:06

2021-04-22 14:44 UTC, sirlensalot commented
We will do this with #1218 instead.

2021-04-22 14:44 UTC, closed without merging