Version upgrade 2.12
kadena-io/chainweb-node pull request #1334
Opened 2022-01-04 19:46 UTC by edmundnoble

2022-01-05 18:09 UTC, larskuhtz requested changes

2022-01-05 18:09 UTC, larskuhtz commented on CHANGELOG.md
> +*   Upgrade Pact version to 4.2.0. (#1323)
Maybe move this to the top of the list, since it is the most important change?

2022-01-05 18:09 UTC, larskuhtz commented on CHANGELOG.md
> +This version will stop working on **2022-02-24T00:00:00Z**.
fyi, this is 6 weeks

2022-01-05 18:09 UTC, larskuhtz commented on chainweb.cabal
> +copyright:    Copyright (C) 2018 - 2022 Kadena LLC
We should also update the copy right date in the LICENSE file.

2022-01-05 18:44 UTC, mightybyte commented on CHANGELOG.md
> +This version will stop working on **2022-02-24T00:00:00Z**.
Confirmed

2022-01-05 18:46 UTC, mightybyte commented on node/ChainwebNode.hs
> +serviceDate = Just "2022-02-24T00:00:00Z"
Confirmed.  Also...this matches the date in the changelog.

2022-01-05 20:19 UTC, larskuhtz approved these changes

2022-01-06 00:49 UTC, sirlensalot approved these changes

2022-01-06 01:06 UTC, merged