Pact 4.6 fork
kadena-io/chainweb-node pull request #1602
Opened 2023-02-07 21:56 UTC by jmcardon

2023-02-08 00:20 UTC, emilypi approved these changes

2023-02-08 00:21 UTC, emilypi commented on src/Chainweb/Version.hs
> +chainweb218Pact Testnet04 = error "todo: fill"
Pending todo's, approved

2023-02-08 00:24 UTC, edmundnoble approved these changes
Pending todo's, approved

2023-02-08 00:24 UTC, edmundnoble commented on src/Chainweb/Version.hs
> +chainweb218Pact _ = const True
Fallthrough case should be `(> 24)`.

2023-02-08 00:24 UTC, jwiegley requested changes

2023-02-08 00:24 UTC, jwiegley commented on cabal.project
> +    tag: 5664e2e2b1833fcb2242c9fd6adbaba7dd8d1f68
This will need to be updated again once https://github.com/kadena-io/pact/pull/1139 is merged.

2023-02-08 18:44 UTC, jwiegley commented on cabal.project
> +    tag: 5664e2e2b1833fcb2242c9fd6adbaba7dd8d1f68
```suggestion
    tag: 6bf5477a6ee3c78faf606471894b3e986deefe3d
```

2023-02-08 18:45 UTC, jwiegley approved these changes

2023-02-08 22:01 UTC, emilypi commented on src/Chainweb/Version.hs
> +chainweb218Pact _ = const True
Addressed in the latest commit

2023-02-09 04:59 UTC, larskuhtz approved these changes

2023-02-09 16:52 UTC, emilypi approved these changes

2023-02-11 02:33 UTC, merged