Add requestKeys logging to execNewBlock
kadena-io/chainweb-node pull request #1704
Opened 2023-07-21 13:40 UTC by ak3n

2023-07-21 15:59 UTC, edmundnoble commented
When we produce a new block, the process looks like:
  * grab a set of transactions `txs` from the mempool such that `sum (map txGasLimit) txs <= blockGasLimit`
  * execute these transactions and record the actual gas used
  * then in a loop:
    * grab a set of transactions `newTxs` from the mempool such that `sum (map txGasLimit) txs + currentlyUsedGas <= blockGasLimit`
      * if this set is empty, we're done
      * if this set is not empty, execute `newTxs` and update the actual gas used to include the amount of gas used by `newTxs`

We call this process "block fill". That's just background on how it works. The trouble is that this code actually only logs the request keys in the first batch of `txs`, ignoring all of the `newTxs`.

2023-07-24 10:11 UTC, ak3n commented
@edmundnoble thanks for the explanation! I was not sure about logging the keys after the refill step.

Take a look again please, we can just reuse the refill result then.

2023-07-24 15:46 UTC, edmundnoble requested changes
Actually let's also do this for execPreInsertCheck in this PR.

2023-07-24 19:14 UTC, edmundnoble approved these changes

2023-07-24 22:18 UTC, chessai approved these changes

2023-07-24 22:33 UTC, merged